### ISSUE TITLE
Support pnpm user agent

### ISSUE THREAD

**Issue by dangreaves** [sktan/aws-codeartifact-proxy#12]
In [proxy.go](https://github.com/sktan/aws-codeartifact-proxy/blob/master/src/tools/proxy.go#L83), there is a conditional which checks if the user agent begins with `npm` to apply specific npm logic, like switching out the registry URL for the proxy URL in responses.

When it comes to registry access, [pnpm](https://pnpm.io/) works the same as npm, so should be fully compatible with this proxy. However, the user agent which pnpm sends is below.

```
pnpm/8.6.3 npm/? node/v16.17.1 darwin arm64
```

This, coupled with the conditional, means that when using pnpm, the proxy responds with the original CodeArtifact URLs for the dist files, resulting in an authentication error, since clients are not authenticated.

I would open a PR for this, but my Go skills aren't too sharp 🙏 

## Workaround

It's possible to work around this issue, by setting the below in an `.npmrc` file local to the project. This updates the user agent which pnpm uses to just `npm` and thus satisfies the conditional in the proxy. However, due to [an issue](https://github.com/pnpm/pnpm/issues/6701) with pnpm, it only works with a project specific `.npmrc` file.

```
user-agent=npm
```

**Comment by sktan** [comment]
This should be solved by #13 and available via version`v0.5.0`
